defaults:
  - _self_

action_dim: 15
observation_dim: 63
base_dir: exp1

model:
  kl_weight: 10
  num_actions: 16  # how many actions to predict, 16 in BiGym paper
  action_dim: ${action_dim}
  observation_dim: ${observation_dim}
  latent_dim: 32
  hidden_dim: 512

  backbone:
    type: 'resnet18'
    train_backbone: true
    return_interm_layers: false
    dilation: false  # ??
    positional_encoding:
      type: 'sine'
      hidden_dim: ${model.hidden_dim}

  transformer:
    enc_layers: 4
    dec_layers: 6
    dim_feedforward: 2048
    hidden_dim: ${model.hidden_dim}
    dropout: 0.1
    nheads: 8
    pre_norm: false

optimizer:
  lr_backbone: 1e-5
  lr: 5e-5
  weight_decay: 1e-4

data:
    data_dir: ${base_dir}/data
    demos_cnt: 60
    train_ratio: 0.95
    batch_size: 64
    num_workers: 4
    actions_num: ${model.num_actions}

training:
  seed: 0
  num_epochs: 500
  train_steps: None  # redefine inside
  val_steps: None  # redefine inside
  save_ckpt_frequency: 10
  log_interval: 5
  ckpt_dir: ${base_dir}/ckpts

evaluation:
  seed: 0
  ckpt_path: ${training.ckpt_dir}/best_policy.ckpt
  temporal_agg: false
  max_timesteps: 200  # episode length
  num_rollouts: 3
  stats_file_path: ${data.data_dir}/train/stats.json
  k: 0.01
  save_video: true
  videos_dir: ${base_dir}/videos

env:
  _target_: bigym.envs.reach_target.ReachTarget
  action_mode:
    _target_: bigym.action_modes.JointPositionActionMode
    absolute: true
    floating_base: true
  observation_config:
    _target_: bigym.utils.observation_config.ObservationConfig
    cameras:
      - 
        _target_: bigym.utils.observation_config.CameraConfig
        name: 'head'
        rgb: true
        depth: false
        resolution: [84, 84]
      - 
        _target_: bigym.utils.observation_config.CameraConfig
        name: 'right_wrist'
        rgb: true
        depth: false
        resolution: [84, 84]
      - 
        _target_: bigym.utils.observation_config.CameraConfig
        name: 'left_wrist'
        rgb: true
        depth: false
        resolution: [84, 84]
    proprioception: true
  render_mode: 'rgb_array'
  control_frequency: 50  # as in ACT paper
  start_seed: 0
