defaults:
  - _self_

model:
  kl_weight: 10
  num_actions: 16
  action_dim: 0  # redefine
  observation_dim: 0  # redefine
  latent_dim: 32

  backbone:
    type: 'resnet18'
    train_backbone: true
    return_interm_layers: false
    dilation: false  # ??
    positional_encoding:
      type: 'sine'
      hidden_dim: 256

  transformer:
    enc_layers: 4
    dec_layers: 6
    dim_feedforward: 2048
    hidden_dim: 256
    dropout: 0.1
    nheads: 8
    num_queries: 400
    pre_norm: false

optimizer:
  lr_backbone: 1e-5
  main:
    _target_: torch.optim.AdamW
    lr: 1e-4
    weight_decay: 1e-4

data:
    demos_cnt: 5
    train_ratio: 0.15
    batch_size: 64
    num_workers: 4

    actions_num: 16  # how many actions to predict, 16 in BiGym paper

training:
  seed: 0

  train_steps: None
  ckpt_dir: 'ckpts'
  save_ckpt_frequency: 100
  log_interval: 1
